version: '3'

services:
  ui:
    container_name: spotify-recommendations-ui
    working_dir: /usr/src/ui
    ports:
      - "8000:8000"
    volumes:
      - ./ui/:/usr/src/ui
      - ./data:/usr/src/ui/data
    command: streamlit run app.py --server.port 8000 --server.runOnSave true
    build: .

