name: deploy app
run-name: ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      image_name:
        description: "image name"
        default: "httpd"

jobs:
  deploy_app:
    name: "Deploy APP"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        if: ${{ github.event.inputs.action == 'apply' }}
        uses: google-github-actions/setup-gcloud@v1

      - name: Docker run
        run: >
          gcloud compute ssh --zone europe-central2-a spotify-vm -- 'docker run {{ github.event.inputs.httpd }} -d --rm -p 8000:8000'